
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class AplikasiPerhitunganDiskon extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPerhitunganDiskon
     */
    public AplikasiPerhitunganDiskon() {
        initComponents();
        ComboBoxDiskon.addItem("0%");
        ComboBoxDiskon.addItem("10%");
        ComboBoxDiskon.addItem("20%");
        ComboBoxDiskon.addItem("30%");
        ComboBoxDiskon.addItem("40%");
        ComboBoxDiskon.addItem("50%");
        ComboBoxDiskon.addItem("60%");
        ComboBoxDiskon.addItem("70%");
        ComboBoxDiskon.addItem("80%");
        ComboBoxDiskon.addItem("90%");
        ComboBoxDiskon.addItem("100%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelHargaAwal = new javax.swing.JLabel();
        LabelUntung = new javax.swing.JLabel();
        SliderDiskon = new javax.swing.JSlider();
        ComboBoxDiskon = new javax.swing.JComboBox<>();
        HargaAwal = new javax.swing.JTextField();
        LabelDiskon = new javax.swing.JLabel();
        LabelPersentase = new javax.swing.JLabel();
        Keuntungan = new javax.swing.JTextField();
        LabelHargaAkhir = new javax.swing.JLabel();
        HargaAkhir = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        ScrollPane = new javax.swing.JScrollPane();
        Riwayat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        LabelKodeKupon = new javax.swing.JLabel();
        KodeKupon = new javax.swing.JTextField();
        TombolKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Perhitugnan Diskon");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        LabelHargaAwal.setText("Harga Awal");

        LabelUntung.setText("Keuntungan");

        SliderDiskon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderDiskonStateChanged(evt);
            }
        });

        ComboBoxDiskon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxDiskonItemStateChanged(evt);
            }
        });
        ComboBoxDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxDiskonActionPerformed(evt);
            }
        });

        HargaAwal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HargaAwalKeyTyped(evt);
            }
        });

        LabelDiskon.setText("Diskon");

        LabelPersentase.setText("Persentase Diskon");

        LabelHargaAkhir.setText("Harga Akhir");

        Hitung.setBackground(new java.awt.Color(204, 255, 204));
        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });

        Riwayat.setColumns(20);
        Riwayat.setRows(5);
        ScrollPane.setViewportView(Riwayat);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Perhitungan Diskon");

        LabelKodeKupon.setText("Kode Kupon");

        TombolKeluar.setForeground(new java.awt.Color(255, 51, 51));
        TombolKeluar.setText("Keluar");
        TombolKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TombolKeluar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelPersentase)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SliderDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(ComboBoxDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelDiskon)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelHargaAwal)
                                .addGap(76, 76, 76)
                                .addComponent(HargaAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(Hitung))
                            .addComponent(LabelHargaAkhir)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelUntung)
                                    .addComponent(LabelKodeKupon))
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Keuntungan)
                                    .addComponent(HargaAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(KodeKupon))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(140, 140, 140))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HargaAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelHargaAwal))
                        .addGap(15, 15, 15)
                        .addComponent(LabelDiskon)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SliderDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelPersentase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Hitung)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelUntung)
                            .addComponent(Keuntungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelKodeKupon)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelHargaAkhir)
                                    .addComponent(HargaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(KodeKupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(TombolKeluar)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        try {
            // Cek apakah HargaAwal kosong atau tidak valid
            if (HargaAwal.getText().isEmpty() || HargaAwal.getText().equals("Rp ")) {
                JOptionPane.showMessageDialog(this, "Silakan masukkan harga asli.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Ambil HargaAwal dari JTextField dan hilangkan "Rp " di depannya
            double hargaAwal = Double.parseDouble(HargaAwal.getText().replace("Rp ", "").replace(",", ""));

            // Tentukan diskon persentase dari SliderDiskon atau ComboBoxDiskon
            int DiskonPersen;
            if (SliderDiskon.getValue() > 0) {
                DiskonPersen = SliderDiskon.getValue();
            } else {
                String diskonStr = (String) ComboBoxDiskon.getSelectedItem();
                DiskonPersen = Integer.parseInt(diskonStr.replace("%", ""));
            }

            // Ambil kode kupon dari JTextField
            String kodeKupon = KodeKupon.getText().trim();

            // Tambahan diskon jika kode kupon valid
            if (kodeKupon.equalsIgnoreCase("DISKON5%")) {
                DiskonPersen += 5;
                JOptionPane.showMessageDialog(this, "Kode kupon 5% berhasil diterapkan!", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else if (kodeKupon.equalsIgnoreCase("DISKON10%")) {
                DiskonPersen += 10;
                JOptionPane.showMessageDialog(this, "Kode kupon 10% berhasil diterapkan!", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else if (kodeKupon.equalsIgnoreCase("DISKON15%")) {
                DiskonPersen += 15;
                JOptionPane.showMessageDialog(this, "Kode kupon 15% berhasil diterapkan!", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else if (!kodeKupon.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Kode kupon tidak ada.", "Info", JOptionPane.INFORMATION_MESSAGE);
            }


            // Hitung Keuntungan dan Harga Akhir
            double keuntungan = hargaAwal * DiskonPersen / 100;
            double hargaAkhir = hargaAwal - keuntungan;

            // Tampilkan hasil pada JTextField dengan prefix "Rp "
            Keuntungan.setText("Rp " + String.format("%,.2f", keuntungan));
            HargaAkhir.setText("Rp " + String.format("%,.2f", hargaAkhir));

            // Tambahkan hasil ke riwayat
            String hasilRiwayat = "Harga Awal: Rp " + String.format("%,.2f", hargaAwal) +
                                  ", Diskon: " + DiskonPersen + "%" +
                                  ", Penghematan: Rp " + String.format("%,.2f", keuntungan) +
                                  ", Harga Akhir: Rp " + String.format("%,.2f", hargaAkhir) + "\n";
            Riwayat.append(hasilRiwayat);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan nilai yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void ComboBoxDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxDiskonActionPerformed

    private void ComboBoxDiskonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxDiskonItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        String diskonStr = (String) ComboBoxDiskon.getSelectedItem();
        int DiskonPersen = Integer.parseInt(diskonStr.replace("%", ""));
    }
    }//GEN-LAST:event_ComboBoxDiskonItemStateChanged

    private void SliderDiskonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderDiskonStateChanged
        // TODO add your handling code here:
         // Update label persentase sesuai dengan nilai slider
        int sliderValue = SliderDiskon.getValue();
        LabelPersentase.setText("Persentase Diskon : " + sliderValue + "%");
    }//GEN-LAST:event_SliderDiskonStateChanged

    private void HargaAwalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HargaAwalKeyTyped
        // TODO add your handling code here:
        if (!HargaAwal.getText().startsWith("Rp ")) {
            HargaAwal.setText("Rp ");
        }
    }//GEN-LAST:event_HargaAwalKeyTyped

    private void TombolKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TombolKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPerhitunganDiskon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxDiskon;
    private javax.swing.JTextField HargaAkhir;
    private javax.swing.JTextField HargaAwal;
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField Keuntungan;
    private javax.swing.JTextField KodeKupon;
    private javax.swing.JLabel LabelDiskon;
    private javax.swing.JLabel LabelHargaAkhir;
    private javax.swing.JLabel LabelHargaAwal;
    private javax.swing.JLabel LabelKodeKupon;
    private javax.swing.JLabel LabelPersentase;
    private javax.swing.JLabel LabelUntung;
    private javax.swing.JTextArea Riwayat;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JSlider SliderDiskon;
    private javax.swing.JButton TombolKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
